spring:
  application:
    name: algatransito-api
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/algatransito?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    password: ''
